version: '3'

services:
  backend:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"


  frontend:
    build: ./assessment-frontend
    volumes:
      - ./assessment-frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
